### ISSUE TITLE
error on my server

### ISSUE THREAD

**Issue by jinyu8779** [NoahDragon/hexo-theme-react#1]
Unhandled rejection TypeError: /opt/lyd/themes/react/layout/sections/_services.jade:8
    6|         h3 What we offer
    7|         .row.big-icons-row.service-items.center
  > 8|             each service in site.data['services']
    9|                 +service(service)
    10|
Cannot read property 'length' of undefined
    at Object.eval (eval at exports.compile (/opt/lyd/node_modules/_jade@1.11.0@jade/lib/index.js:218:8), <anonymous>:1125:32)
    at Object.jade_interp [as blocks] (eval at exports.compile (/opt/lyd/node_modules/_jade@1.11.0@jade/lib/index.js:218:8), <anonymous>:1150:4)
    at eval (eval at exports.compile (/opt/lyd/node_modules/_jade@1.11.0@jade/lib/index.js:218:8), <anonymous>:5192:22)
    at eval (eval at exports.compile (/opt/lyd/node_modules/_jade@1.11.0@jade/lib/index.js:218:8), <anonymous>:5353:22)
    at res (/opt/lyd/node_modules/_jade@1.11.0@jade/lib/index.js:219:38)
    at Theme._View.View._compiled.locals [as _compiled] (/opt/lyd/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/opt/lyd/node_modules/hexo/lib/theme/view.js:29:15)
    at route.set (/opt/lyd/node_modules/hexo/lib/hexo/index.js:386:29)
    at tryCatcher (/opt/lyd/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/lyd/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/lyd/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:443:10)
    at resume_ (_stream_readable.js:823:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by WuZhuoran** [comment]
I got the same error.

```
ERROR /Users/oliver/Documents/git/YiGu-Studio.github.io/themes/react/layout/sections/_services.jade:8
    6|         h3 What we offer
    7|         .row.big-icons-row.service-items.center
  > 8|             each service in site.data['services']
    9|                 +service(service)
    10| 

Cannot read property 'length' of undefined
```

**Comment by Uzizkp** [comment]
I have the same problem
`Cannot read property 'length' of undefined`

**Comment by itrice** [comment]
I got the same error.

```
TypeError: H:\Workspace4ASP\01 AYZR\03 Source Code\WebSite\blog\themes\react\layout\sections\_services.jade:8
    6|         h3 What we offer
    7|         .row.big-icons-row.service-items.center
  > 8|             each service in site.data['services']
    9|                 service(service)
    10| 

Cannot read property 'length' of undefined 
```

**Comment by LinaWwang** [comment]
I got the same error.

```
    6|         h3 What we offer
    7|         .row.big-icons-row.service-items.center
  > 8|             each service in site.data['services']
    9|                 +service(service)
```

**Comment by dtdivecenter** [comment]
I got the same error.
ERROR TypeError: C:\dtdivecenter\themes\react\layout\sections\_services.pug:8
    6|         h3 What we offer
    7|         .row.big-icons-row.service-items.center
  > 8|             each service in site.data['services']
    9|                 +service(service)
    10|

Cannot read property 'length' of undefined
    at Object.eval (eval at wrap (C:\dtdivecenter\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1828:32)
    at Object.eval (eval at wrap (C:\dtdivecenter\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1843:4)
    at Object.pug_interp [as blocks] (eval at wrap (C:\dtdivecenter\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:

**Comment by Gullintani** [comment]
This might be a plugin version problem, please refer to https://github.com/next-theme/hexo-theme-next/issues/66
